version: "3.3"
services:
  syslogserver:
    image: aboudev/syslog-sl
    hostname: SL
    build: docker
    container_name: SL
    restart: always
    volumes:
      - "/var/log:/var/log"
    networks:
      site-local:
        ipv4_address: 10.1.2.3
    cap_add:
      - SYSLOG
      - NET_ADMIN
      - NET_BROADCAST
networks:
  site-local:
    external: true
