version: "3.3"
services: 
  syslogserver: 
    image: aboudev/syslog 
    hostname: serv_syslog 
    container_name: serv_syslog 
    restart: always
    volumes: 
      - "/var/log:/var/log" 
    ports: 
      - 514:514
      - 514:514/udp
    cap_add:
      - SYSLOG
