version: "3.3"
services:
  syslogserver:
    image: aboudev/syslog
    hostname: SA
    container_name: SA
    restart: always
    volumes:
      - "/var/log:/var/log"
    ports:
      - 516:516
      - 516:516/udp
    cap_add:
      - SYSLOG
      - NET_ADMIN
      - NET_BROADCAST
networks:
  default:
    external:
      name: sp-sd-network


