version: "3.3"
services:
  syslogserver:
    image: aboudev/syslog-sa
    hostname: SA
    build: docker
    container_name: SA
    restart: always
    volumes:
      - "/var/log:/var/log"
    networks:
      sp-sd-network:
        ipv4_address: 10.1.1.4
      site-local:
        ipv4_address: 10.1.2.2
    cap_add:
      - SYSLOG
      - NET_ADMIN
      - NET_BROADCAST
networks:
  sp-sd-network:
    external: true
  site-local:
    external: true
