version: "3.3"
services:
  syslogserver:
    image: aboudev/syslog-sp
    hostname: SP
    build: docker
    container_name: SP
    restart: always
    volumes:
      - "/var/log:/var/log"
    cap_add:
      - SYSLOG
      - NET_ADMIN
      - NET_BROADCAST
networks:
  default:
    external:
      name: sp-sd-network


