version: "3.3"
services:
  syslogserver:
    image: aboudev/syslog
    hostname: SD
    build: docker
    container_name: SD
    restart: always
    volumes:
      - "/var/log:/var/log"
    cap_add:
      - SYSLOG
      - NET_ADMIN
      - NET_BROADCAST
networks:
  default:
    external:
      name: sp-sd-network


