version: "3.3"
services:
  syslogserver:
    image: aboudev/syslog-sd
    hostname: SP
    build: docker
    container_name: SD
    restart: always
    volumes:
      - "/var/log:/var/log"
    networks:
      sp-sd-network:
        ipv4_address: 10.1.1.3
      backup:
        ipv4_address: 10.1.3.3
    cap_add:
      - SYSLOG
      - NET_ADMIN
      - NET_BROADCAST
networks:
  sp-sd-network:
    external: true
  backup:
    external: true
